Repository MindPort-GmbH/VR-Builder, pull requests merged in 2025-03, with the labels that each got.

#291 MP-3242 Fixed wrong handling of scene objects initialization
  Source/Core/Runtime/SceneObjects/ProcessSceneObject.cs
Labels: bug

#295 Move refresh registry check out of process scene object class
  Source/Core/Editor/UI/ProcessSceneObjectEditor.cs
  Source/Core/Runtime/Configuration/RuntimeConfigurator.cs
  Source/Core/Runtime/SceneObjects/GuidBasedSceneObjectRegistry.cs
  Source/Core/Runtime/SceneObjects/ProcessSceneObject.cs
Labels: Review effort 3/5

#292 Updates for VIROO integration
  Source/Core/Editor/Input/InputEditorUtils.cs
  Source/Core/Resources/Prefabs/DefaultWorldConsole.prefab
  Source/Core/Resources/Prefabs/DefaultWorldConsole.prefab.meta
  Source/Core/Runtime/Configuration/BaseRuntimeConfiguration.cs
  Source/Core/Runtime/ProcessController/BasicProcessLoader.cs
  Source/Core/Runtime/Properties/LockableProperty.cs
  Source/Core/Runtime/UI/Console.meta
  Source/Core/Runtime/UI/Console/ConsoleElement.uxml
  Source/Core/Runtime/UI/Console/ConsoleElement.uxml.meta
  Source/Core/Runtime/UI/Console/ConsoleTransformHandler.cs
  Source/Core/Runtime/UI/Console/ConsoleTransformHandler.cs.meta
  Source/Core/Runtime/UI/Console/DefaultRuntimeTheme.tss
  Source/Core/Runtime/UI/Console/DefaultRuntimeTheme.tss.meta
  Source/Core/Runtime/UI/Console/ILogConsole.cs
  Source/Core/Runtime/UI/Console/ILogConsole.cs.meta
  Source/Core/Runtime/UI/Console/LogConsole.cs
  Source/Core/Runtime/UI/Console/LogConsole.cs.meta
  Source/Core/Runtime/UI/Console/LogConsole.renderTexture
  Source/Core/Runtime/UI/Console/LogConsole.renderTexture.meta
  Source/Core/Runtime/UI/Console/LogConsole.uxml
  Source/Core/Runtime/UI/Console/LogConsole.uxml.meta
  Source/Core/Runtime/UI/Console/LogConsoleMaterial.mat
  Source/Core/Runtime/UI/Console/LogConsoleMaterial.mat.meta
  Source/Core/Runtime/UI/Console/LogConsolePanelSettings.asset
  Source/Core/Runtime/UI/Console/LogConsolePanelSettings.asset.meta
  Source/Core/Runtime/UI/Console/LogMessage.cs
  Source/Core/Runtime/UI/Console/LogMessage.cs.meta
  Source/Core/Runtime/Utils/ComponentUtils.cs
  Source/Core/Runtime/Utils/ComponentUtils.cs.meta
  Source/Core/Runtime/Utils/WorldConsole.cs
  Source/Core/Runtime/Utils/WorldConsole.cs.meta
  Source/XRInteraction/Source/Runtime/XRI/ClimbTeleportDestinationIndicator.cs.meta
  Source/XRInteraction/Source/Runtime/XRI/ComponentLocatorUtility.cs.meta
  Source/XRInteraction/Source/Runtime/XRI/StarterAssets/ControllerAnimator.cs.meta
  Source/XRInteraction/Source/Runtime/XRI/StarterAssets/ControllerInputActionManager.cs.meta
  Source/XRInteraction/Source/Runtime/XRI/StarterAssets/DynamicMoveProvider.cs.meta
  Source/XRInteraction/Source/Runtime/XRI/StarterAssets/GazeInputManager.cs.meta
Labels: Review effort 4/5
